### ISSUE TITLE
how to call pom-debloat 

### ISSUE THREAD

**Issue by monperrus** [castor-software/royal-debloat#2]
Hi Cesar,

With @henrikplate, we're looking at https://github.com/castor-software/royal-debloat/tree/master/jdbl-pom#usage

Once you modified the `pom.xml`:

* what's the command line to execute goal `pom-debloat`?
* what's the result of this command? does it modify the current pom?

Thanks!

**Comment by cesarsotovalero** [comment]
Hi Martin

I'm glad to hear that good people is interested in this project. Thanks for sharing ;)

To answer your questions:
- Once built and  installed, the plugin can be executed running `mvn jdbl-pom:debloat-pom`
- It does not modify the current `pom.xml`. Instead, it creates a  `pom-debloated.xml` file in the root of the project and gives some additional information about dependencies in the terminal

 I extended the plugin's [readme](https://github.com/castor-software/royal-debloat/blob/master/jdbl-pom/jdbl-pom-maven-plugin/README.md) and made some refactoring. This tool is still WIP.

**Comment by monperrus** [comment]
Thanks! To avoid confusion, what about merging `jdbl-pom/README.md` and `jdbl-pom/jdbl-pom-maven-plugin/README.md`?

**Comment by cesarsotovalero** [comment]
Good suggestion. I modified the READMEs accordingly. 
The idea is to have a monorepo of debloat tools, with a structure similar to [royal-chaos](https://github.com/KTH/royal-chaos).

**Comment by monperrus** [comment]
Great, thanks a lot. Closing the issue.
