### ISSUE TITLE
Integrate with gradle

### ISSUE THREAD

**Issue by bbaudry** [castor-software/royal-debloat#5]
Extract / build three modules
- [ ] bytecode analysis logic 
- [ ] Maven plugin based on the first module
- [ ] Gradle plugin based on the first module

**Comment by cesarsotovalero** [comment]
We moved DepClean to [this](https://github.com/castor-software/depclean) repo and keep it as a GitHub sub-module of the `royal-debloat` repo.

The following refactor were implemented:
- [X] bytecode analysis logic (the bytecode logic was moved to the module called `depclean-core`)
- [X] Maven plugin based on the first module (the maven `depclean-maven-plugin` is a module that depends on the `depclean-core` module)
- [X] Gradle plugin based on the first module (the `depclean-gradle-plugin` extends `depclean-core` and uses the java and maven gradle plugins to simulate a maven build)

**Note:** The gradle plugin needs additional improvements (see [issues](https://github.com/castor-software/depclean/issues/2))
